#
# Sparse matrix algebra
#

OBJ = sparsecolmat.o mathtools.o amoeba.o amotry.o nrexit.o bessj0.o gasdev.o ran1.o ran2.o sort.o indexx.o golden.o mnbrak.o

LIBNAME = sparsemat

include ../Makefile.gen

