#
# Construction librairie tomographie
#
# LD Fri Apr 13
# TSsinogramme.o is now under the Anne Bilgot responsability 

OBJ = projection.o sinogramme.o  FBDetLine.o GFBsinogramme.o FBsinogramme.o FBconvol.o pseudofct.o PsConvol.o integ.o


LIBNAME =  tomographie

include ../Makefile.gen

